"""Generate docs/wiki/Camp-Objects.md from the addon catalog and tools/wiki_objects.json.

    python tools/gen_wiki.py            # write the page
    python tools/gen_wiki.py --check    # exit 1 if the committed page is out of date

Tiers, skills, places, replacements and class-buff exclusivity are read from
Campkeeper/Data/Catalog.lua, so the wiki changes together with the addon.
English names and effects live in tools/wiki_objects.json.
"""
import argparse
import json
import sys
from pathlib import Path

from lupa import lua51

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / "Campkeeper" / "Data" / "Catalog.lua"
TEXTS = ROOT / "tools" / "wiki_objects.json"
OUT = ROOT / "docs" / "wiki" / "Camp-Objects.md"

_LOAD = """
return function(src)
  local f, err = loadstring(src, "@Catalog.lua")
  if not f then error(err, 0) end
  local ns = {}
  f("Campkeeper", ns)
  return ns.CatalogData
end
"""


def _py(v):
    """Lua table -> dict, or list when its keys are 1..n."""
    if not hasattr(v, "items"):
        return v
    d = {k: _py(x) for k, x in v.items()}
    if d and all(isinstance(k, int) for k in d) and sorted(d) == list(range(1, len(d) + 1)):
        return [d[i] for i in range(1, len(d) + 1)]
    return d


def load_catalog(path: Path = CATALOG):
    lua = lua51.LuaRuntime(unpack_returned_tuples=True, encoding="utf-8")
    return _py(lua.execute(_LOAD)(path.read_text(encoding="utf-8-sig")))


def render(catalog, texts):
    objects, names = catalog["objects"], texts["objects"]
    missing = [k for k in catalog["order"] if k not in names]
    if missing:
        raise KeyError("no wiki text for: " + ", ".join(missing))

    def name(key):
        return names[key]["name"]

    def buffs(keys):
        return " / ".join(texts["classBuffs"][b] for b in keys)

    families = []
    for key in catalog["order"]:
        fam = objects[key]["family"]
        if fam not in families:
            families.append(fam)

    out = [
        "# Camp objects",
        "",
        "<!-- Generated by tools/gen_wiki.py from Campkeeper/Data/Catalog.lua and tools/wiki_objects.json. Do not edit by hand. -->",
        "",
        "Every campfire and camp object in *World of Warcraft: Forever*, as the Campkeeper catalog knows them. "
        "Data from the beta client 1.60.1 (build 70334); numbers can still change before launch. "
        "In game the names come from your client, so they are in your language.",
        "",
        "## Campfires",
        "",
        "A campfire is the heart of a camp: every other object needs one nearby. All fires are made with Cooking.",
        "",
        "| Campfire | Cooking | Places for objects |",
        "|---|---|---|",
    ]
    for f in catalog["fires"]:
        out.append(f"| {texts['fires'][str(f['tier'])]} | {f['skill']} | {f['slots']} |")

    out += [
        "",
        "## Bonuses at a glance",
        "",
        "The first-tier object of most professions gives a stat bonus to everyone who sits by the fire. "
        "Each bonus is mutually exclusive with one class buff: you get one or the other, not both. "
        "Campkeeper marks such objects in the camp panel and the planner skips them when the group has that class.",
        "",
        "| Profession | Object | Bonus | Does not stack with |",
        "|---|---|---|---|",
    ]
    for fam in families:
        keys = [k for k in catalog["order"] if objects[k]["family"] == fam]
        base = next((k for k in keys if objects[k]["tier"] == 1 and objects[k].get("exclusiveWith")), None)
        if base:
            o = objects[base]
            out.append(f"| {texts['professions'][o['profession']]} | {name(base)} | "
                       f"{names[base]['effect']} | {buffs(o['exclusiveWith'])} |")

    out += [
        "",
        "Higher tiers placed over a first-tier object keep its bonus, so you lose nothing by upgrading.",
        "",
        "## By profession",
        "",
        "Skill is the profession skill needed to make and place the object.",
    ]
    for fam in families:
        keys = [k for k in catalog["order"] if objects[k]["family"] == fam]
        prof = texts["professions"][objects[keys[0]]["profession"]]
        out += ["", f"### {prof}", "", "| Tier | Object | Skill | What it does |", "|---|---|---|---|"]
        for k in keys:
            o = objects[k]
            parts = [names[k]["effect"]] if names[k]["effect"] else []
            base = o.get("replaces")
            if base and objects[base]["kind"] in ("buff", "rest"):
                parts.append(f"Also gives the {name(base)} bonus; place it over the {name(base)} to upgrade.")
            elif base:
                parts.append(f"Place it over the {name(base)} to upgrade.")
            elif o["tier"] == 1 and o.get("exclusiveWith"):
                parts.append(f"Does not stack with {buffs(o['exclusiveWith'])}.")
            out.append(f"| {o['tier']} | {name(k)} | {o['skill']} | {' '.join(parts)} |")

    out += [
        "",
        "## Rules that apply to every object",
        "",
        "- All camping items share **one cooldown** per character: 5 minutes in the current beta build, "
        "although the item tooltips still say 1 hour.",
        "- An object needs a campfire nearby, and the fire has a limited number of places (see above).",
        "- Bonuses come from sitting by the fire for 1 minute; they last 1 hour as **Camp Benefits**.",
        "",
        "See also: [[Camping guide|Camping-Guide]].",
        "",
    ]
    return "\n".join(out)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=str(OUT))
    ap.add_argument("--check", action="store_true", help="do not write; exit 1 if output differs")
    args = ap.parse_args(argv)
    out = Path(args.out)
    texts = json.loads(TEXTS.read_text(encoding="utf-8"))
    try:
        text = render(load_catalog(), texts)
    except KeyError as e:
        print(f"error: {e.args[0]}", file=sys.stderr)
        return 1
    if args.check:
        current = out.read_text(encoding="utf-8") if out.is_file() else ""
        if current != text:
            print(f"{out} is out of date; run tools/gen_wiki.py", file=sys.stderr)
            return 1
        print("wiki page up to date")
        return 0
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
